# Generated by Django 4.2.30 on 2026-09-27 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='owner',
            field=models.OneToOneField(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_publisher',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[('reader', 'Reader'),
                         ('journalist', 'Journalist'),
                         ('editor', 'Editor'),
                         ('publisher', 'Publisher')],
                         max_length=20),
        ),
    ]
