# Generated by Django 4.2.30 on 2026-09-27 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_publisher_owner_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='owner',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_publisher',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
